import torch.nn as nn

class ConvBlock(nn.Module):# this is a simple convolutional block that consists of two convolutional layers with ReLU activation. 
    #It is used in the UNet architecture to extract features from the input image. 
    # The first convolutional layer takes in the input channels and outputs the specified number of output channels, while the second convolutional layer 
    # takes in the output from the first layer and produces the final output of the block. By stacking multiple ConvBlocks together, we can create a deeper 
    # network that can capture more complex features in the input image, which is important for accurately predicting the noise in the diffusion process.
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.net = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, 3, padding=1),
            nn.ReLU(),
            nn.Conv2d(out_ch, out_ch, 3, padding=1),
            nn.ReLU()
        )

    def forward(self, x):
        return self.net(x)
    
'''
Downsample → understand context
Upsample → reconstruct image
Skip connections preserve detail
'''
# this is simple UNet, not the full one used in diffusion models. We will add time embedding and attention later
class UNet(nn.Module):# this is the UNet architecture that we will use for our diffusion model. 
    # It consists of a downsampling path, an upsampling path, and skip connections between the two paths. 
    # The downsampling path consists of two convolutional blocks followed by max pooling, while the upsampling path consists of a transposed convolution followed by a convolutional block. 
    # The final output is generated by a 1x1 convolution that maps the features to the desired number of output channels (in this case, 3 for RGB images). 
    # This UNet architecture allows us to capture both local and global features in the input image, which is important for accurately predicting the noise in the diffusion process.
    def __init__(self):
        super().__init__()

        self.down1 = ConvBlock(3, 64)
        self.pool = nn.MaxPool2d(2)
        self.down2 = ConvBlock(64, 128)

        self.up = nn.ConvTranspose2d(128, 64, 2, stride=2)
        self.up_conv = ConvBlock(128, 64)

        self.final = nn.Conv2d(64, 3, 1)

    def forward(self, x):
        d1 = self.down1(x)
        d2 = self.down2(self.pool(d1))

        up = self.up(d2)
        concat = torch.cat([up, d1], dim=1)

        out = self.up_conv(concat)

        return self.final(out)

# model doesn’t know how much noise is present, so we need to give it that information. We can do this with time embedding. 
# Time embedding is a way to encode the timestep into a vector that can be added to the input of the model. 
# This way, the model can learn to predict the noise based on the timestep.
class TimeEmbedding(nn.Module):
    def __init__(self, dim):
        super().__init__()
        self.embed = nn.Embedding(1000, dim)

    def forward(self, t):
        return self.embed(t)