class Encoder(nn.Module): # The Encoder processes the input sequence and produces a sequence of hidden states. It uses an LSTMCell to process the input one time step at a time, and it returns the final hidden states as well as the outputs from all time steps.
    def __init__(self, input_size, hidden_size):
        super().__init__()
        self.cell = LSTMCell(input_size, hidden_size) # The LSTMCell is defined in lstm_cell.py and implements the logic of a single LSTM time step.

    def forward(self, x): # x is the input sequence of shape (batch_size, seq_len, input_size). The forward method processes the sequence one time step at a time, updating the hidden and cell states at each step.
        batch_size, seq_len, _ = x.size()

        h = torch.zeros(batch_size, self.cell.hidden_size).to(x.device) # The hidden and cell states are initialized to zeros at the beginning of the sequence.
        c = torch.zeros(batch_size, self.cell.hidden_size).to(x.device) 

        outputs = []

        for t in range(seq_len): # The input at each time step is passed through the LSTMCell along with the previous hidden and cell states to get the new states, which are then stored in the outputs list.
            h, c = self.cell(x[:, t, :], h, c)
            outputs.append(h)

        return torch.stack(outputs, dim=1), (h, c) # The outputs from all time steps are stacked together to form the final output sequence, and the final hidden and cell states are returned as well.
    
class Decoder(nn.Module): # The Decoder generates the output sequence one time step at a time, using the hidden states from the Encoder and the previously generated outputs. It also incorporates an attention mechanism to focus on different parts of the Encoder's outputs at each time step.
    def __init__(self, hidden_size, output_size):
        super().__init__()
        self.cell = LSTMCell(output_size, hidden_size)# The Decoder uses an LSTMCell to generate the output sequence, similar to the Encoder, but it takes the previously generated output as input at each time step instead of the original input sequence.
        self.attention = Attention(hidden_size) # The Attention mechanism allows the Decoder to focus on different parts of the Encoder's outputs at each time step, which can improve performance on tasks like machine translation.
        # The attention scores are computed using a feedforward network that takes the Decoder's hidden state and the Encoder's outputs as input.

        self.fc = nn.Linear(hidden_size * 2, output_size) # The output of the Decoder is generated by combining the Decoder's hidden state and the context vector from the attention mechanism, and passing it through a linear layer to get the final output for each time step.

    def forward(self, x, hidden, cell, encoder_outputs): # x is the input at the current time step (which can be the previous output during training), hidden and cell are the current hidden and cell states of the Decoder, and encoder_outputs are the outputs from the Encoder that will be used for attention.
        h, c = self.cell(x, hidden, cell)

        context, _ = self.attention(h, encoder_outputs) 

        out = torch.cat([h, context], dim=1) # The Decoder's hidden state and the context vector from the attention mechanism are concatenated together to form the input to the final linear layer, which generates the output for the current time step.
        out = self.fc(out)

        return out, h, c
    
class Seq2Seq(nn.Module): # The Seq2Seq model combines the Encoder and Decoder to create a complete sequence-to-sequence architecture. 
    # It takes an input sequence, processes it through the Encoder, and then generates an output sequence using the Decoder, while also applying attention to focus on relevant parts of the Encoder's outputs.
    def __init__(self, encoder, decoder):
        super().__init__()
        self.encoder = encoder
        self.decoder = decoder

    def forward(self, src, tgt):
        encoder_outputs, (h, c) = self.encoder(src) # The input sequence is passed through the Encoder to get the encoder outputs and the final hidden and cell states, which will be used to initialize the Decoder.

        outputs = []

        x = tgt[:, 0, :]  # start token

        for t in range(1, tgt.size(1)): # The Decoder generates the output sequence one time step at a time, using the previously generated output as input for the next time step. 
            out, h, c = self.decoder(x, h, c, encoder_outputs)
            outputs.append(out)
            x = out  # teacher forcing can be added later

        return torch.stack(outputs, dim=1)# The outputs from all time steps are stacked together to form the final output sequence, which is returned by the forward method.